---------------------------- Disclaimer ------------------------------
    Here, the term 'administrators' refers to Some People

 In no event will the administrators of this program be liable to you
   or anybody else for any damages, including any general, special,
 incidental, or consquential damages, arising out of use or inability
   to use the program, or arising from the actions of you or other
                       users of the program.
   This includes, but is by no means limited to, the fact that any
statement made by any user of the program is not necessarily the view
	   of the administrators, nor supported by them.
	
     By using this program you are explicitly accepting the above
  terms, for this and any future uses of the program, and that you
indemnify the administrators against any damages arising in any way to
    do with your, or anybody elses, use or misuse of the program.

    Send 'continue' to accept these terms, or 'end' to disconnect.
----------------------------------------------------------------------
