---------------------------------- MOTD --------------------------------------
        Thanks to Burble from Foothills for the original code <8-) 
          Also Athanasius and Grim for further work done since.
------------------------------------------------------------------------------
    Any problems/comments contact Admin on:-   summink@somewhere
------------------------------------------------------------------------------
