------------------------------NEW USERS-------------------------------
     Summink is a chat program based around EW-too by Simon Marsh

    It is here for one and all as a place to just relax and chat.
     Look around and enjoy yourself. If you find that you like it
   and would like a Permanent Account, then just ask one
 of our SuperUsers for "Residency".  If you don't know who they are,
  just ask another user, or type 'lsu'.  If you need information on
    how to use Summink, just type "help" once you are online.

      If you have any problems these are the guys to contact ...
                       Summink@somwhere
----------------------------------------------------------------------
